name: Build/release

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install
        working-directory: ./app
        run: |
          npm install
      - name: Build Windows
        if: matrix.os == 'windows-latest'
        working-directory: ./app
        run: npm run build:win && dir dist
      - name: Build Linux
        if: matrix.os == 'ubuntu-latest'
        working-directory: ./app
        run: npm run build:linux && ls -alF dist
      - name: Build macOS
        if: matrix.os == 'macos-latest'
        working-directory: ./app
        run: npm run build:mac && ls -alF dist
      - name: Update release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            app/dist/*.msi
            app/dist/*.dmg
            app/dist/*.zip
            app/dist/*.snap
            app/dist/*.AppImage
          target_commitish: ${{ github.sha }}
          fail_on_unmatched_files: true
#          token: ${{ secrets.GITHUB_TOKEN }}
